name: 'AutoQA Pilot Test Execution'
description: 'Execute automated tests using AutoQA Pilot platform'
author: 'AutoQA Team'

branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  api-url:
    description: 'AutoQA Pilot API URL'
    required: true
    default: 'https://api.autoqa-pilot.com'

  api-key:
    description: 'AutoQA Pilot API key for authentication'
    required: true

  project-id:
    description: 'Project ID to run tests for'
    required: true

  test-suite-id:
    description: 'Specific test suite ID (optional)'
    required: false

  environment:
    description: 'Target environment for testing'
    required: false
    default: 'staging'

  wait-for-completion:
    description: 'Wait for test execution to complete'
    required: false
    default: 'true'

  timeout:
    description: 'Maximum time to wait for completion (in minutes)'
    required: false
    default: '30'

  fail-on-test-failure:
    description: 'Fail the action if tests fail'
    required: false
    default: 'true'

outputs:
  execution-id:
    description: 'Unique execution ID for the test run'

  status:
    description: 'Final execution status (completed, failed, cancelled)'

  results-url:
    description: 'URL to view detailed test results'

  total-tests:
    description: 'Total number of tests executed'

  passed-tests:
    description: 'Number of tests that passed'

  failed-tests:
    description: 'Number of tests that failed'

  duration:
    description: 'Total execution duration in seconds'

runs:
  using: 'node20'
  main: 'dist/index.js'
